# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3"

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
  cloudsql:
  ssl-certs:

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./ssl-certs/:/ssl-certs/
    depends_on:
      - ckan
    ports:
      - "443:443"


  ckan:
    container_name: ckan
    build:
      context: ../../
      args:
          - CKAN_SITE_URL=${CKAN_SITE_URL}
    links:
      - cloudsql-proxy
    depends_on:
      - cloudsql-proxy
      - solr
      - redis
    expose:
      - "5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=${CKAN_SQLALCHEMY_URL}
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_SOLR_USER=${CKAN_SOLR_USER}
      - CKAN_SOLR_PASSWORD=${CKAN_SOLR_PASSWORD}
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - CKAN_OAUTH2_AUTHORIZATION_ENDPOINT=${CKAN_OAUTH2_AUTHORIZATION_ENDPOINT}
      - CKAN_OAUTH2_TOKEN_ENDPOINT=${CKAN_OAUTH2_TOKEN_ENDPOINT}
      - CKAN_OAUTH2_CLIENT_ID=${CKAN_OAUTH2_CLIENT_ID}
      - CKAN_OAUTH2_CLIENT_SECRET=${CKAN_OAUTH2_CLIENT_SECRET}
      - CKAN_OAUTH2_PROFILE_API_URL=${CKAN_OAUTH2_PROFILE_API_URL}
      - CKAN_OAUTH2_SCOPE=${CKAN_OAUTH2_SCOPE}
      - CKAN_OAUTH2_PROFILE_API_USER_FIELD=${CKAN_OAUTH2_PROFILE_API_USER_FIELD}
      - CKAN_OAUTH2_PROFILE_API_MAIL_FIELD=${CKAN_OAUTH2_PROFILE_API_MAIL_FIELD}
      - CKAN_PRIVATE_ORGS=${CKAN_PRIVATE_ORGS}
      - OAUTHLIB_INSECURE_TRANSPORT=${OAUTHLIB_INSECURE_TRANSPORT}
      - OAUTHLIB_RELAX_TOKEN_SCOPE=${OAUTHLIB_RELAX_TOKEN_SCOPE}
      - GCP_SQL_INSTANCE=${GCP_SQL_INSTANCE}
    volumes:
      - ckan_config:/etc/ckan
      - ckan_home:/usr/lib/ckan
      - ckan_storage:/var/lib/ckan
      - /mnt/stateful_partition/cloudsql:/cloudsql

  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command: /cloud_sql_proxy --dir=/cloudsql -instances=${GCP_SQL_INSTANCE}
    volumes:
      - /mnt/stateful_partition/cloudsql:/cloudsql
    restart: always

  solr:
    container_name: solr
    build:
      context: ../../
      dockerfile: contrib/docker-GCP/solr/Dockerfile
    ports:
      - "127.0.0.1:${SOLR_PORT}:8983"

  redis:
    container_name: redis
    image: redis:latest
